export const {
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_ADMIN_ID,
  VK_TOKEN,
  VK_GROUP_ID,
  VK_CONFIRMATION,
  VK_SECRET,
  SUPABASE_URL,
  SUPABASE_KEY,
  NODE_ENV,
  VERCEL_PROJECT_PRODUCTION_URL,
} = process.env;
